In [3]:
# Instalação das dependências
import sys
import subprocess
import os

# Install requirements from the parent directory
requirements_path = os.path.join('..', 'requirements.txt')
subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-r', requirements_path])

0

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns   
import sklearn
import pandas as pd

In [3]:
base_navios = pd.read_csv('Dados navios Hackathon.xlsx - Dados navios.csv')
relatorio_iws = pd.read_csv('Relatorios IWS.xlsx - Planilha1.csv')
resultado_consumo = pd.read_csv('ResultadoQueryConsumo.csv')
resultado_eventos = pd.read_csv('ResultadoQueryEventos.csv')


base_navios.head()

,Nome do navio,Classe,Tipo,Porte Bruto,Comprimento total (m),Boca (m),Calado (m),Pontal (m)
0,RAFAEL SANTOS,Suezmax,Petroleiro,156628,"274,2",48,17,"23,2"
1,HENRIQUE ALVES,Suezmax,Petroleiro,157700,"274,2",48,17,"23,2"
2,VICTOR OLIVEIRA,Suezmax,Petroleiro,156492,"274,2",48,17,"23,2"
3,FELIPE RIBEIRO,Suezmax,Petroleiro,157700,"274,2",48,17,"23,2"
4,GISELLE CARVALHO,Suezmax,Petroleiro,156504,"274,2",48,17,"23,2"

In [4]:
relatorio_iws['Embarcação'] = relatorio_iws['Embarcação'].str.upper()
relatorio_iws.head()

,Classe,Embarcação,Sigla,Data,Local de realização,Regiões do casco limpas,Condição geral da embarcação,Tipo de incrustação da embarcação,Condição do fundo chato,Tipo de incrustação do fundo chato,Condição do costado,Tipo de incrustação do costado,Condição do hélice,Tipo de incrustação do hélice
0,Aframax,CARLA SILVA,CSI,8/29/2025,Angra dos Reis/RJ,NaN,100%,"Craca, alga e limo",100%,Incrustações duras e moles,"100%, 20%",Moles (100%) e Duras (20%),100%,Moles e Duras
1,Suezmax,RAUL MARTINS,RMA,3/30/2023,São Sebastião/SP,NaN,10%,Duras no fundo,10%,Duras,Não consta no relatório,Não consta no relatório,40%,Moles e Duras
2,MR2,EDUARDO COSTA,EDC,1/11/2025,São Sebastião/SP,NaN,10%,Moles e duras,10%,Moles (5%) e Duras (5%),5%,Moles,80%,Moles
3,Suezmax,VICTOR OLIVEIRA,VOL,3/3/2021,Salvador/BA,NaN,30%,Cracas e limo,30%,Cracas e limo,30%,Cracas e limo,90%,Cracas e limo
4,Aframax,CARLA SILVA,CSI,8/21/2021,Angra dos Reis/RJ,NaN,100%,Alga e limo,100%,Alga e limo,100%,Alga e limo,85%,"Alga, limo e calcárea"

In [5]:
resultado_consumo.head()

    SESSION_ID  CONSUMED_QUANTITY DESCRIPTION
0  39800000086               47.0   LSHFO 0.5
1  39800000088               48.0   LSHFO 0.5
2  39800000091               46.0   LSHFO 0.5
3  39800000093               47.0   LSHFO 0.5
4  39800000095               46.0   LSHFO 0.5

In [7]:
# 1° - igualar o nome sessionId para SESSION_ID em todas as bases

In [6]:
resultado_eventos_ID = resultado_eventos.rename(columns={'sessionId': 'SESSION_ID'})
resultado_eventos_ID.head()

,SESSION_ID,shipName,class,eventName,startGMTDate,endGMTDate,duration,distance,aftDraft,fwdDraft,...,displacement,beaufortScale,seaCondition,beaufortScaleDesc,seaConditionDesc,speed,speedGps,Porto,decLatitude,decLongitude
0,39800000084,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-24 11:00:00,2021-05-25 11:00:00,24.0,282.0,14.9,14.0,...,128703.71,5.0,NaN,5 - Fresh breeze,3 - Slight,11.75,11.75,NaN,-32.1300,15.1300
1,39800000086,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-25 11:00:00,2021-05-26 11:00:00,24.0,254.0,14.9,14.0,...,128703.72,NaN,NaN,3 - Gentle breeze,2 - Smooth (wavelets),10.58,10.58,NaN,-30.3800,10.2500
2,39800000088,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-26 11:00:00,2021-05-27 12:00:00,25.0,295.0,14.9,14.0,...,128703.72,NaN,NaN,3 - Gentle breeze,3 - Slight,11.80,11.80,NaN,-28.5568,5.2018
3,39800000091,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-27 12:00:00,2021-05-28 12:00:00,24.0,284.0,14.9,14.0,...,128703.72,NaN,NaN,3 - Gentle breeze,2 - Smooth (wavelets),11.83,11.83,NaN,-27.1400,0.2100
4,39800000093,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-28 10:00:00,2021-05-29 11:00:00,25.0,293.0,14.9,14.0,...,128703.72,NaN,NaN,1 - Light air,2 - Smooth (wavelets),11.72,11.72,NaN,-25.2800,-4.4273

In [9]:
# adicionar outro tratamento: embarcação em base_eventos é igual a shipName em base_consumo

In [7]:
resultado_eventos_consumo = resultado_consumo.merge(resultado_eventos_ID, on='SESSION_ID', how='inner')
resultado_eventos_consumo.head()

,SESSION_ID,CONSUMED_QUANTITY,DESCRIPTION,shipName,class,eventName,startGMTDate,endGMTDate,duration,distance,...,displacement,beaufortScale,seaCondition,beaufortScaleDesc,seaConditionDesc,speed,speedGps,Porto,decLatitude,decLongitude
0,39800000086,47.0,LSHFO 0.5,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-25 11:00:00,2021-05-26 11:00:00,24.0,254.0,...,128703.72,NaN,NaN,3 - Gentle breeze,2 - Smooth (wavelets),10.58,10.58,NaN,-30.3800,10.2500
1,39800000088,48.0,LSHFO 0.5,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-26 11:00:00,2021-05-27 12:00:00,25.0,295.0,...,128703.72,NaN,NaN,3 - Gentle breeze,3 - Slight,11.80,11.80,NaN,-28.5568,5.2018
2,39800000091,46.0,LSHFO 0.5,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-27 12:00:00,2021-05-28 12:00:00,24.0,284.0,...,128703.72,NaN,NaN,3 - Gentle breeze,2 - Smooth (wavelets),11.83,11.83,NaN,-27.1400,0.2100
3,39800000093,47.0,LSHFO 0.5,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-28 10:00:00,2021-05-29 11:00:00,25.0,293.0,...,128703.72,NaN,NaN,1 - Light air,2 - Smooth (wavelets),11.72,11.72,NaN,-25.2800,-4.4273
4,39800000095,46.0,LSHFO 0.5,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-29 11:00:00,2021-05-30 11:00:00,24.0,282.0,...,128703.72,NaN,NaN,1 - Light air,5 - Rough,11.75,11.75,NaN,-23.4545,-9.2853

In [10]:
relatorio_geral = relatorio_iws.join(resultado_eventos_consumo, how = "left")
relatorio_geral.head()

,Classe,Embarcação,Sigla,Data,Local de realização,Regiões do casco limpas,Condição geral da embarcação,Tipo de incrustação da embarcação,Condição do fundo chato,Tipo de incrustação do fundo chato,...,displacement,beaufortScale,seaCondition,beaufortScaleDesc,seaConditionDesc,speed,speedGps,Porto,decLatitude,decLongitude
0,Aframax,CARLA SILVA,CSI,8/29/2025,Angra dos Reis/RJ,NaN,100%,"Craca, alga e limo",100%,Incrustações duras e moles,...,128703.72,NaN,NaN,3 - Gentle breeze,2 - Smooth (wavelets),10.58,10.58,NaN,-30.3800,10.2500
1,Suezmax,RAUL MARTINS,RMA,3/30/2023,São Sebastião/SP,NaN,10%,Duras no fundo,10%,Duras,...,128703.72,NaN,NaN,3 - Gentle breeze,3 - Slight,11.80,11.80,NaN,-28.5568,5.2018
2,MR2,EDUARDO COSTA,EDC,1/11/2025,São Sebastião/SP,NaN,10%,Moles e duras,10%,Moles (5%) e Duras (5%),...,128703.72,NaN,NaN,3 - Gentle breeze,2 - Smooth (wavelets),11.83,11.83,NaN,-27.1400,0.2100
3,Suezmax,VICTOR OLIVEIRA,VOL,3/3/2021,Salvador/BA,NaN,30%,Cracas e limo,30%,Cracas e limo,...,128703.72,NaN,NaN,1 - Light air,2 - Smooth (wavelets),11.72,11.72,NaN,-25.2800,-4.4273
4,Aframax,CARLA SILVA,CSI,8/21/2021,Angra dos Reis/RJ,NaN,100%,Alga e limo,100%,Alga e limo,...,128703.72,NaN,NaN,1 - Light air,5 - Rough,11.75,11.75,NaN,-23.4545,-9.2853

In [11]:
# que tipo de análise eu preciso agr?
# quero saber o consumo de combustível por tipo de embarcação

# preciso saber quais os tipos de shipName existem
resultado_eventos_consumo['shipName'].unique()

array(['DANIEL PEREIRA', 'ROMARIO SILVA', 'LUCAS MENDONÇA',
       'MARCOS CAVALCANTI', 'THIAGO FERNANDES', 'MARIA VALENTINA',
       'FÁBIO SANTOS', 'BRUNO LIMA', 'GISELLE CARVALHO',
       'VICTOR OLIVEIRA', 'CARLA SILVA', 'HENRIQUE ALVES', 'RAUL MARTINS',
       'RAFAEL SANTOS', 'RENATO GOMES', 'PAULO MOURA', 'RICARDO BARBOSA',
       'FELIPE RIBEIRO', 'GABRIELA MARTINS', 'RODRIGO PINHEIRO',
       'EDUARDO COSTA'], dtype=object)

### 1° - classificação por shipType
> O que eu consigo achar de insights através do tipo do navio?

In [12]:
print(relatorio_geral.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 38 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Classe                              29 non-null     object
 1   Embarcação                          29 non-null     object
 2   Sigla                               29 non-null     object
 3   Data                                29 non-null     object
 4   Local de realização                 29 non-null     object
 5   Regiões do casco limpas             11 non-null     object
 6   Condição geral da embarcação        29 non-null     object
 7   Tipo de incrustação da embarcação   27 non-null     object
 8   Condição do fundo chato             29 non-null     object
 9   Tipo de incrustação do fundo chato  24 non-null     object
 10  Condição do costado                 29 non-null     object
 11  Tipo de incrustação do costado      27 non-null     object
 12  Condição do hélice                  28 non-null     object
 13  Tipo de incrustação do hélice       26 non-null     object
 14  SESSION_ID                          29 non-null     int64
 15  CONSUMED_QUANTITY                   21 non-null     float64
 16  DESCRIPTION                         29 non-null     object
 17  shipName                            29 non-null     object
 18  class                               29 non-null     object
 19  eventName                           29 non-null     object
 20  startGMTDate                        29 non-null     object
 21  endGMTDate                          29 non-null     object
 22  duration                            29 non-null     float64
 23  distance                            27 non-null     float64
 24  aftDraft                            22 non-null     float64
 25  fwdDraft                            22 non-null     float64
 26  midDraft                            22 non-null     float64
 27  TRIM                                22 non-null     float64
 28  displacement                        22 non-null     float64
 29  beaufortScale                       0 non-null      float64
 30  seaCondition                        0 non-null      float64
 31  beaufortScaleDesc                   22 non-null     object
 32  seaConditionDesc                    22 non-null     object
 33  speed                               27 non-null     float64
 34  speedGps                            27 non-null     float64
 35  Porto                               4 non-null      object
 36  decLatitude                         25 non-null     float64
 37  decLongitude                        25 non-null     float64
dtypes: float64(14), int64(1), object(23)
memory usage: 8.7+ KB
None

In [ ]:
# de acordo com o tipo do navio ( nome ), posso fazer análises como:
# desses navios,  qual a condição de cada?
# de acordo com a condição, qual o consumo médio?

# para isso, eu posso usar árvore de decisão

In [13]:
# --- DATA PREPARATION & CLEANING ---

# 1. Date Parsing & Standardization
# We need to handle mixed formats (e.g., DD/MM/YYYY and MM/DD/YYYY) carefully.
def parse_dates_smart(date_series):
    # Try parsing with dayfirst=True (common in Brazil)
    return pd.to_datetime(date_series, dayfirst=True, errors='coerce')

relatorio_iws['Data_Clean'] = parse_dates_smart(relatorio_iws['Data'])
resultado_eventos['startGMTDate'] = pd.to_datetime(resultado_eventos['startGMTDate'], errors='coerce')

print("Date parsing complete. Null dates in inspections:", relatorio_iws['Data_Clean'].isnull().sum())

Date parsing complete. Null dates in inspections: 1

C:\Users\Aluno\AppData\Local\Temp\ipykernel_18512\1476823938.py:7: UserWarning: Parsing dates in %m/%d/%Y format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  return pd.to_datetime(date_series, dayfirst=True, errors='coerce')

In [14]:
# 2. Target Variable Engineering: Fouling Score (0-100)
import re

def extract_fouling_score(text):
    if pd.isna(text):
        return None
    text = str(text).lower()
    
    # Case 1: Direct percentage (e.g., '100%', '10%')
    match = re.search(r'(\d+)%', text)
    if match:
        return float(match.group(1))
    
    # Case 2: Norman Scale (1-5 often used, mapping to 0-100)
    # Assuming 1=Clean(0), 5=Heavy(100) roughly, or just keeping raw if it's a scale.
    # Let's look for single digits if no % exists
    match_digit = re.search(r'^\s*(\d+)\s*$', text)
    if match_digit:
        val = float(match_digit.group(1))
        if val <= 5: # Likely Norman scale
            return val * 20 # Map 1-5 to 20-100 roughly
        return val
        
    # Case 3: Text Descriptions (Heuristic Mapping)
    if 'limo' in text and 'craca' not in text:
        return 20 # Light fouling
    if 'craca' in text:
        return 80 # Heavy fouling
    if 'alga' in text:
        return 40 # Medium fouling
        
    return None

# Apply to key columns
relatorio_iws['Fouling_Score_General'] = relatorio_iws['Condição geral da embarcação'].apply(extract_fouling_score)
relatorio_iws['Fouling_Score_Hull'] = relatorio_iws['Condição do fundo chato'].apply(extract_fouling_score)

# Fill missing scores with an average or default if needed, for now let's keep NaNs
print(relatorio_iws[['Condição geral da embarcação', 'Fouling_Score_General']].head(10))

  Condição geral da embarcação  Fouling_Score_General
0                         100%                  100.0
1                          10%                   10.0
2                          10%                   10.0
3                          30%                   30.0
4                         100%                  100.0
5                          10%                   10.0
6                          20%                   20.0
7                         100%                  100.0
8                          90%                   90.0
9                          80%                   80.0

In [18]:
# 3. Advanced Merging: Propagating Inspection Data
# We want to associate each voyage event with the *most recent* inspection BEFORE that voyage.

# Sort both datasets by date
relatorio_iws = relatorio_iws.dropna(subset=['Data_Clean'])
relatorio_iws = relatorio_iws.sort_values('Data_Clean')
resultado_eventos = resultado_eventos.sort_values('startGMTDate')

# Ensure ship names match exactly (uppercase already done)
relatorio_iws['Embarcação'] = relatorio_iws['Embarcação'].str.strip().str.upper()
resultado_eventos['shipName'] = resultado_eventos['shipName'].str.strip().str.upper()

# Use merge_asof to find the nearest prior inspection
# Note: merge_asof requires sorted keys
merged_data = pd.merge_asof(
    resultado_eventos,
    relatorio_iws[['Embarcação', 'Data_Clean', 'Fouling_Score_General', 'Fouling_Score_Hull']],
    left_on='startGMTDate',
    right_on='Data_Clean',
    left_by='shipName',
    right_by='Embarcação',
    direction='backward' # Look for the closest past date
)

# Calculate 'Days Since Inspection'
merged_data['Days_Since_Inspection'] = (merged_data['startGMTDate'] - merged_data['Data_Clean']).dt.days

print("Merge complete. Sample of new columns:")
print(merged_data[['shipName', 'startGMTDate', 'Data_Clean', 'Fouling_Score_General', 'Days_Since_Inspection']].head())

Merge complete. Sample of new columns:
           shipName        startGMTDate Data_Clean  Fouling_Score_General  \
0  RODRIGO PINHEIRO 2021-03-22 12:00:00        NaT                    NaN
1  RODRIGO PINHEIRO 2021-03-22 12:15:00        NaT                    NaN
2  RODRIGO PINHEIRO 2021-03-22 13:25:00        NaT                    NaN
3  RODRIGO PINHEIRO 2021-03-25 19:45:00        NaT                    NaN
4  RODRIGO PINHEIRO 2021-03-25 20:00:00        NaT                    NaN

   Days_Since_Inspection
0                    NaN
1                    NaN
2                    NaN
3                    NaN
4                    NaN

In [19]:
# 4. Final Dataset for Model
# Now you have 'merged_data' with:
# - Operational data (Speed, Consumption, Weather)
# - Fouling State (Fouling_Score_General)
# - Time factor (Days_Since_Inspection)

# You can now drop rows where we have no inspection data if strict training is needed
final_df = merged_data.dropna(subset=['Fouling_Score_General'])
print(f"Final dataset shape: {final_df.shape}")

Final dataset shape: (20705, 27)

In [20]:
# 5. Incorporating AIS Data
import glob

# Path to AIS data
ais_path = 'Dados AIS frota TP/*.csv'
ais_files = glob.glob(ais_path)

print(f"Found {len(ais_files)} AIS files.")

# Load and concatenate all AIS files
ais_dfs = []
for f in ais_files:
    try:
        df = pd.read_csv(f)
        # Extract ship name from filename if not in columns, but it seems to be in 'NOME'
        ais_dfs.append(df)
    except Exception as e:
        print(f"Error reading {f}: {e}")

if ais_dfs:
    ais_df = pd.concat(ais_dfs, ignore_index=True)
    print("AIS Data Loaded. Shape:", ais_df.shape)
    print(ais_df.head())
else:
    print("No AIS data loaded.")

Found 20 AIS files.
AIS Data Loaded. Shape: (415724, 6)
         NOME             DATAHORA  RUMO  VELOCIDADE   LATITUDE  LONGITUDE
0  BRUNO LIMA  2023-11-25 05:58:41  58.1        12.2 -24.954948 -46.857981
1  BRUNO LIMA  2023-11-25 06:04:02  58.5        12.2 -24.946165 -46.840565
2  BRUNO LIMA  2023-11-25 06:26:12  59.2        12.1 -24.910048 -46.768348
3  BRUNO LIMA  2023-11-25 06:57:31  69.1        12.3 -24.860081 -46.665115
4  BRUNO LIMA  2023-11-25 07:46:41  62.9        12.2 -24.777231 -46.506615

In [21]:
# Preprocessing AIS Data
if 'ais_df' in locals():
    # Convert timestamp
    ais_df['DATAHORA'] = pd.to_datetime(ais_df['DATAHORA'], errors='coerce')
    
    # Create Date column for daily aggregation
    ais_df['Date'] = ais_df['DATAHORA'].dt.floor('D')
    
    # Clean Speed (remove outliers/errors)
    # Assuming speed is in knots. > 30 knots is unlikely for these tankers.
    ais_df = ais_df[(ais_df['VELOCIDADE'] >= 0) & (ais_df['VELOCIDADE'] < 30)]
    
    # Normalize Ship Name
    ais_df['NOME'] = ais_df['NOME'].str.strip().str.upper()
    
    print("AIS Data Preprocessed.")

AIS Data Preprocessed.

In [22]:
# Aggregating AIS Data by Day and Ship
if 'ais_df' in locals():
    ais_daily = ais_df.groupby(['NOME', 'Date']).agg(
        AIS_Speed_Mean=('VELOCIDADE', 'mean'),
        AIS_Speed_Std=('VELOCIDADE', 'std'),
        AIS_Data_Count=('VELOCIDADE', 'count')
    ).reset_index()
    
    print("AIS Daily Aggregation Complete. Shape:", ais_daily.shape)
    print(ais_daily.head())

AIS Daily Aggregation Complete. Shape: (7836, 5)
         NOME       Date  AIS_Speed_Mean  AIS_Speed_Std  AIS_Data_Count
0  BRUNO LIMA 2023-11-25       12.088235       0.404279              68
1  BRUNO LIMA 2023-11-26        4.788776       5.284521              98
2  BRUNO LIMA 2023-11-27        0.183019       1.290756              53
3  BRUNO LIMA 2023-11-28       13.707000       0.870882             100
4  BRUNO LIMA 2023-11-29        2.300000       4.491356              58

In [23]:
# Merging AIS Data with Main Dataset
if 'merged_data' in locals() and 'ais_daily' in locals():
    # Create Date column in merged_data for joining
    merged_data['Date'] = merged_data['startGMTDate'].dt.floor('D')
    
    # Merge
    # We use left join to keep all events, adding AIS info where available
    merged_data_ais = pd.merge(
        merged_data,
        ais_daily,
        left_on=['shipName', 'Date'],
        right_on=['NOME', 'Date'],
        how='left'
    )
    
    print("Merge with AIS complete. New Shape:", merged_data_ais.shape)
    print(merged_data_ais[['shipName', 'Date', 'AIS_Speed_Mean', 'Fouling_Score_General']].head())
    
    # Check correlation
    corr = merged_data_ais[['Fouling_Score_General', 'AIS_Speed_Mean']].corr()
    print("\nCorrelation between Fouling Score and AIS Speed:")
    print(corr)

Merge with AIS complete. New Shape: (50904, 32)
           shipName       Date  AIS_Speed_Mean  Fouling_Score_General
0  RODRIGO PINHEIRO 2021-03-22             NaN                    NaN
1  RODRIGO PINHEIRO 2021-03-22             NaN                    NaN
2  RODRIGO PINHEIRO 2021-03-22             NaN                    NaN
3  RODRIGO PINHEIRO 2021-03-25             NaN                    NaN
4  RODRIGO PINHEIRO 2021-03-25             NaN                    NaN

Correlation between Fouling Score and AIS Speed:
                       Fouling_Score_General  AIS_Speed_Mean
Fouling_Score_General               1.000000       -0.128627
AIS_Speed_Mean                     -0.128627        1.000000