In [29]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns   
import sklearn

import pandas as pd

In [30]:
base_navios = pd.read_csv('Dados navios Hackathon.xlsx - Dados navios.csv')
relatorio_iws = pd.read_csv('Relatorios IWS.xlsx - Planilha1.csv')
resultado_consumo = pd.read_csv('ResultadoQueryConsumo.csv')
resultado_eventos = pd.read_csv('ResultadoQueryEventos.csv')


base_navios.head()

,Nome do navio,Classe,Tipo,Porte Bruto,Comprimento total (m),Boca (m),Calado (m),Pontal (m)
0,RAFAEL SANTOS,Suezmax,Petroleiro,156628,"274,2",48,17,"23,2"
1,HENRIQUE ALVES,Suezmax,Petroleiro,157700,"274,2",48,17,"23,2"
2,VICTOR OLIVEIRA,Suezmax,Petroleiro,156492,"274,2",48,17,"23,2"
3,FELIPE RIBEIRO,Suezmax,Petroleiro,157700,"274,2",48,17,"23,2"
4,GISELLE CARVALHO,Suezmax,Petroleiro,156504,"274,2",48,17,"23,2"

In [43]:
base_navios = base_navios.rename(columns={"Nome do Navio": "shipName"})

In [45]:
relatorio_iws['Embarcação'] = relatorio_iws['Embarcação'].str.upper()
relatorio_iws.head()

,Classe,Embarcação,Sigla,Data,Local de realização,Regiões do casco limpas,Condição geral da embarcação,Tipo de incrustação da embarcação,Condição do fundo chato,Tipo de incrustação do fundo chato,Condição do costado,Tipo de incrustação do costado,Condição do hélice,Tipo de incrustação do hélice
0,Aframax,CARLA SILVA,CSI,8/29/2025,Angra dos Reis/RJ,NaN,100%,"Craca, alga e limo",100%,Incrustações duras e moles,"100%, 20%",Moles (100%) e Duras (20%),100%,Moles e Duras
1,Suezmax,RAUL MARTINS,RMA,3/30/2023,São Sebastião/SP,NaN,10%,Duras no fundo,10%,Duras,Não consta no relatório,Não consta no relatório,40%,Moles e Duras
2,MR2,EDUARDO COSTA,EDC,1/11/2025,São Sebastião/SP,NaN,10%,Moles e duras,10%,Moles (5%) e Duras (5%),5%,Moles,80%,Moles
3,Suezmax,VICTOR OLIVEIRA,VOL,3/3/2021,Salvador/BA,NaN,30%,Cracas e limo,30%,Cracas e limo,30%,Cracas e limo,90%,Cracas e limo
4,Aframax,CARLA SILVA,CSI,8/21/2021,Angra dos Reis/RJ,NaN,100%,Alga e limo,100%,Alga e limo,100%,Alga e limo,85%,"Alga, limo e calcárea"

In [59]:
resultado_consumo.head()

    SESSION_ID  CONSUMED_QUANTITY DESCRIPTION
0  39800000086               47.0   LSHFO 0.5
1  39800000088               48.0   LSHFO 0.5
2  39800000091               46.0   LSHFO 0.5
3  39800000093               47.0   LSHFO 0.5
4  39800000095               46.0   LSHFO 0.5

In [33]:
# 1° - igualar o nome sessionId para SESSION_ID em todas as bases

In [34]:
resultado_eventos_ID = resultado_eventos.rename(columns={'sessionId': 'SESSION_ID'})
resultado_eventos_ID.head()

,SESSION_ID,shipName,class,eventName,startGMTDate,endGMTDate,duration,distance,aftDraft,fwdDraft,...,displacement,beaufortScale,seaCondition,beaufortScaleDesc,seaConditionDesc,speed,speedGps,Porto,decLatitude,decLongitude
0,39800000084,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-24 11:00:00,2021-05-25 11:00:00,24.0,282.0,14.9,14.0,...,128703.71,5.0,NaN,5 - Fresh breeze,3 - Slight,11.75,11.75,NaN,-32.1300,15.1300
1,39800000086,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-25 11:00:00,2021-05-26 11:00:00,24.0,254.0,14.9,14.0,...,128703.72,NaN,NaN,3 - Gentle breeze,2 - Smooth (wavelets),10.58,10.58,NaN,-30.3800,10.2500
2,39800000088,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-26 11:00:00,2021-05-27 12:00:00,25.0,295.0,14.9,14.0,...,128703.72,NaN,NaN,3 - Gentle breeze,3 - Slight,11.80,11.80,NaN,-28.5568,5.2018
3,39800000091,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-27 12:00:00,2021-05-28 12:00:00,24.0,284.0,14.9,14.0,...,128703.72,NaN,NaN,3 - Gentle breeze,2 - Smooth (wavelets),11.83,11.83,NaN,-27.1400,0.2100
4,39800000093,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-28 10:00:00,2021-05-29 11:00:00,25.0,293.0,14.9,14.0,...,128703.72,NaN,NaN,1 - Light air,2 - Smooth (wavelets),11.72,11.72,NaN,-25.2800,-4.4273

In [35]:
# adicionar outro tratamento: embarcação em base_eventos é igual a shipName em base_consumo

In [36]:
resultado_eventos_consumo = resultado_consumo.merge(resultado_eventos_ID, on='SESSION_ID', how='left')
resultado_eventos_consumo.head()

,SESSION_ID,CONSUMED_QUANTITY,DESCRIPTION,shipName,class,eventName,startGMTDate,endGMTDate,duration,distance,...,displacement,beaufortScale,seaCondition,beaufortScaleDesc,seaConditionDesc,speed,speedGps,Porto,decLatitude,decLongitude
0,39800000086,47.0,LSHFO 0.5,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-25 11:00:00,2021-05-26 11:00:00,24.0,254.0,...,128703.72,NaN,NaN,3 - Gentle breeze,2 - Smooth (wavelets),10.58,10.58,NaN,-30.3800,10.2500
1,39800000088,48.0,LSHFO 0.5,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-26 11:00:00,2021-05-27 12:00:00,25.0,295.0,...,128703.72,NaN,NaN,3 - Gentle breeze,3 - Slight,11.80,11.80,NaN,-28.5568,5.2018
2,39800000091,46.0,LSHFO 0.5,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-27 12:00:00,2021-05-28 12:00:00,24.0,284.0,...,128703.72,NaN,NaN,3 - Gentle breeze,2 - Smooth (wavelets),11.83,11.83,NaN,-27.1400,0.2100
3,39800000093,47.0,LSHFO 0.5,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-28 10:00:00,2021-05-29 11:00:00,25.0,293.0,...,128703.72,NaN,NaN,1 - Light air,2 - Smooth (wavelets),11.72,11.72,NaN,-25.2800,-4.4273
4,39800000095,46.0,LSHFO 0.5,DANIEL PEREIRA,Aframax,NAVEGACAO,2021-05-29 11:00:00,2021-05-30 11:00:00,24.0,282.0,...,128703.72,NaN,NaN,1 - Light air,5 - Rough,11.75,11.75,NaN,-23.4545,-9.2853

In [46]:
resultado_navios = base_navios.merge(resultado_eventos_consumo, left_on='Nome do navio', right_on='shipName', how='left')

In [49]:
relatorio_geral = resultado_navios.merge(relatorio_iws, left_on='shipName', right_on='Embarcação', how='left')
relatorio_geral.head()

,Nome do navio,Classe_x,Tipo,Porte Bruto,Comprimento total (m),Boca (m),Calado (m),Pontal (m),SESSION_ID,CONSUMED_QUANTITY,...,Local de realização,Regiões do casco limpas,Condição geral da embarcação,Tipo de incrustação da embarcação,Condição do fundo chato,Tipo de incrustação do fundo chato,Condição do costado,Tipo de incrustação do costado,Condição do hélice,Tipo de incrustação do hélice
0,RAFAEL SANTOS,Suezmax,Petroleiro,156628,"274,2",48,17,"23,2",43200000508,49.0,...,Singapura,Limpeza geral no casco e propulsor,70-80%,"Craca, alga e limo",60-70%,Cracas e limo,70-80%,"Craca, alga e limo",70-80%,"Cracas, limo e calcárea"
1,RAFAEL SANTOS,Suezmax,Petroleiro,156628,"274,2",48,17,"23,2",43200000508,49.0,...,Angra dos Reis/RJ,Fundo chato e costado de boreste,80%,Moles,0%,NaN,"80%, 15%",Algas (80%) e cracas (15%),Não avaliado,Não avaliado
2,RAFAEL SANTOS,Suezmax,Petroleiro,156628,"274,2",48,17,"23,2",43200000508,49.0,...,Singapura,Fundo chato e costado,45%,Limo leve e algas. Cracas concentradas a ré e ...,20%,Cracas dispersas,45%,Limo leve e algas. Cracas concentradas a ré e ...,Não avaliado,Não avaliado
3,RAFAEL SANTOS,Suezmax,Petroleiro,156628,"274,2",48,17,"23,2",43200000508,NaN,...,Singapura,Limpeza geral no casco e propulsor,70-80%,"Craca, alga e limo",60-70%,Cracas e limo,70-80%,"Craca, alga e limo",70-80%,"Cracas, limo e calcárea"
4,RAFAEL SANTOS,Suezmax,Petroleiro,156628,"274,2",48,17,"23,2",43200000508,NaN,...,Angra dos Reis/RJ,Fundo chato e costado de boreste,80%,Moles,0%,NaN,"80%, 15%",Algas (80%) e cracas (15%),Não avaliado,Não avaliado

In [60]:
# Identificação de colunas Categóricas
categoricas = ["Nome do navio", "Classe_x","Tipo","Local de realização","Regiões do casco limpas","Tipo de incrustação da embarcação","Tipo de incrustação do fundo chato","Tipo de incrustação do costado","Tipo de incrustação do hélice","beaufortScaleDesc","seaConditionDesc","eventName"]

In [51]:
# que tipo de análise eu preciso agr?
# quero saber o consumo de combustível por tipo de embarcação

# preciso saber quais os tipos de shipName existem
relatorio_geral['Classe_x'].unique()

array(['Suezmax', 'Aframax', 'MR 2', 'Gaseiro 7k'], dtype=object)

### 0° - quais são as variáveis mais importantes para o modelo?
> Vou utilizar do método de importância de features e ver no que dá

In [53]:
X = relatorio_geral.drop("Tipo de incrustação da embarcação", axis=1)
y = relatorio_geral["Tipo de incrustação da embarcação"]

In [56]:
# ao ver quantos valores diferentes eu tenho, facilita para entender quais valores são ou não categóricas
X.nunique().sort_values(ascending=False)

SESSION_ID                            36746
startGMTDate                          26913
endGMTDate                            26738
decLongitude                          22429
decLatitude                           22285
duration                               2524
CONSUMED_QUANTITY                      1952
speed                                  1642
speedGps                               1622
distance                                815
displacement                            669
midDraft                                289
aftDraft                                229
fwdDraft                                218
TRIM                                    154
Porto                                    32
Data                                     29
shipName                                 21
Nome do navio                            21
Condição do costado                      21
Porte Bruto                              19
Embarcação                               17
Sigla                                    17
Tipo de incrustação do costado           16
Condição geral da embarcação             16
Tipo de incrustação do hélice            15
Tipo de incrustação do fundo chato       15
Condição do hélice                       14
Condição do fundo chato                  14
beaufortScaleDesc                        13
beaufortScale                            13
Local de realização                      11
seaConditionDesc                         10
DESCRIPTION                               9
Regiões do casco limpas                   7
Pontal (m)                                4
Classe_x                                  4
Comprimento total (m)                     4
class                                     4
Calado (m)                                4
Boca (m)                                  4
Classe_y                                  4
eventName                                 3
Tipo                                      2
seaCondition                              0
dtype: int64

In [67]:
# separar em menos colunas categóricas
limite = 70

categoricas = [
    col for col in X.columns
    if X[col].dtype == 'object' and X[col].nunique() <= limite
]

In [ ]:
# transformando as variáveis em dummies
X = pd.get_dummies(X, columns=categoricas, drop_first=True)

### 1° - remover colunas inúteis

In [ ]:
# para o desenvolvimento do modelo, sempre remova colunas inúteis. 
# colunas de Data e ID geralmente não ajudam no modelo

### 2° - Treino de árvore ( XG Boost )

In [ ]:
from sklearn.ensemble import RandomForestClassifier

modelo = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

modelo.fit(X_encoded, y)

ValueError: could not convert string to float: '2021-09-22 12:00:00'

### 1° - classificação por shipType
> O que eu consigo achar de insights através do tipo do navio?

In [ ]:
# de acordo com o tipo do navio ( nome ), posso fazer análises como:
# desses navios,  qual a condição de cada?
# de acordo com a condição, qual o consumo médio?

# para isso, eu posso usar árvore de decisão

In [ ]:
from sklearn import tree

arvore = tree.DecisionTreeClassifier(random_state=42)
y = df["Tipo de incrustação do fundo chato"]

caracteristicas = ["tipo",""]
x = df[caracteristicas]